# Generated by Django 4.0.6 on 2022-08-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='first_name',
            new_name='Department_name',
        ),
    ]
